### ISSUE TITLE
Only one AudioFormat detected

### ISSUE THREAD

**Issue by pavelkokush** [bome/tritonus#2]
Hello, I want to share my use case and issues that I was faced with.

Use case: 
- Do not use Sun sound impl; 
- Record audio from microphone `16bit LPCM 16kHz sample rate Single channel Little endian audio`; 
- Play `MPEG 2.0 L III cbr48 24000 mono` file;

Environment: Ubuntu 18.04  with k4.15.0-42-generic ALSA.  

I have built all tritonus jars and tritonusalsa.so lib. Added all jars in classpath and .so libs in LD_LIBRARY_PATH. But when I  run it I see only ONE available format: 
`AlsaDataLineMixer.addChanneledAudioFormats(): adding AudioFormat: PCM_SIGNED, 2 channel(s), 16 bit samples, 4 byte frames, -1.0 Hz, -1.0 frames/second, little endian`
 When I run with Sun audio impl - I got 512 audio supported formats (288 hardware formats). It contains format that I need as well.
Why only one format is supported with Tritonus?  

Then I tried to convert mic output from Stereo to Mono (not sure that it is correct usage)  
`AudioSystem.getAudioInputStream(mono, new AudioInputStream(stereo));
`
I got:
```
java.lang.UnsatisfiedLinkError: for org.tritonus.lowlevel.pogg.Packet.malloc()I: library symbol not found
	at org.tritonus.lowlevel.pogg.Packet.<init>(Packet.java)
	at org.tritonus.sampled.convert.pvorbis.VorbisFormatConversionProvider$DecodedVorbisAudioInputStream.init_jorbis(VorbisFormatConversionProvider.java:606)
	at org.tritonus.sampled.convert.pvorbis.VorbisFormatConversionProvider$DecodedVorbisAudioInputStream.<init>(VorbisFormatConversionProvider.java:591)
	at org.tritonus.sampled.convert.pvorbis.VorbisFormatConversionProvider.getAudioInputStream(VorbisFormatConversionProvider.java:165)
	at javax.sound.sampled.AudioSystem$GetAudioInputStreamFormatConversionProviderAction.handleFormatConversionProvider(AudioSystem.java:641)
	at javax.sound.sampled.AudioSystem.doFormatConversionProviderIteration(AudioSystem.java:1380)
	at javax.sound.sampled.AudioSystem.getAudioInputStreamImpl(AudioSystem.java:686)
	at javax.sound.sampled.AudioSystem.getAudioInputStream(AudioSystem.java:724)
```

Same problem (only one format supported) when I try to play MPEG file:
no mixer supporting this type of line: javax.sound.sampled.DataLine$Info@e8e9999[lineClass=interface javax.sound.sampled.Clip]formats:
MPEG2DOT5L2, 2 channel(s), -1 bit samples, -1 byte frames, 11025.0 Hz, -1.0 frames/second, big endian

Any idea how to  fix my use cases with Tritonus? Why only ONE format supported? Does Tritonus "compatible" with latest ALSA  and ready to use nowadays?

**Comment by bome** [comment]
Hi, thanks for testing tritonus. 
The -1 for sample/frame rate means: anything. So you can specify any sample rate you like with the Tritonus ALSA implementation. For the sample format, it only supports the hardware format, so if you want a different format, you can convert it using the API you've tried. Tritonus comes with a PCM2PCM plugin, which should allow you to convert different PCM formats to each other. I believe that it also supports downmixing from stereo to mono.

Regarding the unsatisfied link errors: you should manage which Tritonus plugins you actually need. If you don't need ogg or mp3 (which have additional dependencies), don't add those libs to your classpath. 

Also note that we haven't really worked on Tritonus for approx. 15 years...
Thanks for keeping us posted.
